version: '3.9'

services:
  classcord:
    build: .
    container_name: classcord-server
    ports:
      - "12345:12345"
    volumes:
      - ./logs:/app/logs
      - ./config/database:/app/config/database
      - ./exports:/app/exports
    restart: unless-stopped
